
spring:
  devtools:
    restart:
      pollInterval: 4000

  datasource:
    username: credan_user
    password: Credan888
    url: jdbc:log4jdbc:mysql://192.168.16.200:3306/credan?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

watch:
  path: D:/json_import

server:
  port: 8080
